name: Deploy Python App to Azure Web App (Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: roadobjectdetections # Replace with your App Service name
  AZURE_CONTAINER_REGISTRY: registryfastapi.azurecr.io # Replace with your ACR name (e.g., myappacr.azurecr.io)
  IMAGE_NAME: roadobjectdetection-image # Name for your Docker image
  PYTHON_VERSION: '3.13.3' # Match your Dockerfile base image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production # Or your desired environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }} # Create this secret in GitHub
        password: ${{ secrets.ACR_PASSWORD }} # Create this secret in GitHub

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        # Add build arguments if needed (e.g., for torch CPU-only if not handled by index-url)
        # build-args: |
        #   TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production' # Or your staging slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Or use Azure Login Action
        images: '${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
